// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDYLJ5C3e7VJPk4iduMydGbDXNhKcnktys',
    appId: '1:166357039852:web:32185d514e0b45dd3fc3c9',
    messagingSenderId: '166357039852',
    projectId: 'smart-home-security-syst-48432',
    authDomain: 'smart-home-security-syst-48432.firebaseapp.com',
    databaseURL: 'https://smart-home-security-syst-48432-default-rtdb.firebaseio.com',
    storageBucket: 'smart-home-security-syst-48432.appspot.com',
    measurementId: 'G-X17RVCY1C5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAvTVh6YMJm-Ebq19Mfib9biuG-vBR292U',
    appId: '1:166357039852:android:35bde739c76749443fc3c9',
    messagingSenderId: '166357039852',
    projectId: 'smart-home-security-syst-48432',
    databaseURL: 'https://smart-home-security-syst-48432-default-rtdb.firebaseio.com',
    storageBucket: 'smart-home-security-syst-48432.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDErHFlreirRIPUIq_0z5q0z0O2IaROKsE',
    appId: '1:166357039852:ios:f62264e602c7ff743fc3c9',
    messagingSenderId: '166357039852',
    projectId: 'smart-home-security-syst-48432',
    databaseURL: 'https://smart-home-security-syst-48432-default-rtdb.firebaseio.com',
    storageBucket: 'smart-home-security-syst-48432.appspot.com',
    iosClientId: '166357039852-1vskj3rrfak4o3qvrqp75vkt6v4ev8mg.apps.googleusercontent.com',
    iosBundleId: 'com.example.dracula',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDErHFlreirRIPUIq_0z5q0z0O2IaROKsE',
    appId: '1:166357039852:ios:f62264e602c7ff743fc3c9',
    messagingSenderId: '166357039852',
    projectId: 'smart-home-security-syst-48432',
    databaseURL: 'https://smart-home-security-syst-48432-default-rtdb.firebaseio.com',
    storageBucket: 'smart-home-security-syst-48432.appspot.com',
    iosClientId: '166357039852-1vskj3rrfak4o3qvrqp75vkt6v4ev8mg.apps.googleusercontent.com',
    iosBundleId: 'com.example.dracula',
  );
}
